services:
  - type: web
    name: testdatadogqwer
    runtime: docker
    branch: test-datadog
    rootDir: .
    region: frankfurt
    plan: free
    envVars:
      - key: DD_APM_ENABLED
        value: true
      - key: DD_APM_ENV
        value: prod
      - key: DD_SERVICE
        value: testdatadogqwer
      - key: DD_ENV
        value: prod
      - key: DD_SITE
        value: datadoghq.eu
      - key: DD_BIND_HOST
        value: testdatadogqwer
      - key: DD_HOSTNAME
        value: testdatadogqwer
      - key: DD_HOSTNAME_TRUST_UTS_NAMESPACE
        value: true
      - key: PORT
        value: 8080
      - key: OAUTH2_GOOGLE_CREDENTIALS_FILE
        value: /etc/secrets/clientid.google.json
      - key: DATABASE_URL
        sync: false
      - key: COOKIE_SECRET
        sync: false
      - key: DD_API_KEY
        sync: false
